// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OnFile.Data;
using System;

namespace OnFile.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180619123143_ApplicationUserModelChanged")]
    partial class ApplicationUserModelChanged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("OnFile.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("Firstname")
                        .IsRequired();

                    b.Property<string>("Lastanme")
                        .IsRequired();

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("ProfilePictureUrl");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Sex");

                    b.Property<DateTime>("SignInDate");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.Property<string>("Website");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("OnFile.Models.BuyedFile", b =>
                {
                    b.Property<int>("BuyedFileID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationUserID");

                    b.Property<int>("UploadedFileID");

                    b.HasKey("BuyedFileID");

                    b.HasIndex("ApplicationUserID");

                    b.ToTable("BuyedFile");
                });

            modelBuilder.Entity("OnFile.Models.OptionalPicture", b =>
                {
                    b.Property<int>("OptionalPictureID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasMaxLength(1800);

                    b.Property<int>("UploadedFileID");

                    b.HasKey("OptionalPictureID");

                    b.HasIndex("UploadedFileID");

                    b.ToTable("OptionalPicture");
                });

            modelBuilder.Entity("OnFile.Models.UploadedFile", b =>
                {
                    b.Property<int>("UploadedFileID");

                    b.Property<string>("ApplicationUserID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1800);

                    b.Property<int>("DownloadedTimes");

                    b.Property<DateTime>("LastTimeDownloaded");

                    b.Property<string>("MainPictureUrl")
                        .HasMaxLength(800);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<float>("Price");

                    b.Property<DateTime>("PublishedDate");

                    b.Property<string>("ResourceUrl")
                        .IsRequired()
                        .HasMaxLength(1200);

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(600);

                    b.Property<string>("Visibility")
                        .IsRequired();

                    b.Property<int>("WishListID");

                    b.HasKey("UploadedFileID");

                    b.HasIndex("ApplicationUserID");

                    b.HasIndex("WishListID");

                    b.ToTable("UploadedFile");
                });

            modelBuilder.Entity("OnFile.Models.WishList", b =>
                {
                    b.Property<int>("WishListID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApplicationUserID");

                    b.Property<string>("Description")
                        .HasMaxLength(600);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("WishListID");

                    b.HasIndex("ApplicationUserID");

                    b.ToTable("WishList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("OnFile.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("OnFile.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnFile.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("OnFile.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OnFile.Models.BuyedFile", b =>
                {
                    b.HasOne("OnFile.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("BuyedFiles")
                        .HasForeignKey("ApplicationUserID");
                });

            modelBuilder.Entity("OnFile.Models.OptionalPicture", b =>
                {
                    b.HasOne("OnFile.Models.UploadedFile", "UploadedFile")
                        .WithMany("OptionalPictures")
                        .HasForeignKey("UploadedFileID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OnFile.Models.UploadedFile", b =>
                {
                    b.HasOne("OnFile.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("ApplicationUserID");

                    b.HasOne("OnFile.Models.BuyedFile", "BuyedFile")
                        .WithOne("UploadedFile")
                        .HasForeignKey("OnFile.Models.UploadedFile", "UploadedFileID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OnFile.Models.WishList", "WishList")
                        .WithMany("UploadedFiles")
                        .HasForeignKey("WishListID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OnFile.Models.WishList", b =>
                {
                    b.HasOne("OnFile.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("WishLists")
                        .HasForeignKey("ApplicationUserID");
                });
#pragma warning restore 612, 618
        }
    }
}
